---
repo_url: https://github.com/jonh-carvalho/PBE_25.2_8003
site_author: Jonh Carvalho
site_name: PBE_25.2_8003
copyright: Copyright ©️ 2025, Jonh Carvalho

nav: 
  - Home: index.md
  - Disciplina:
      - Aulas: Disciplina/aulas.md
      - Ambiente: Disciplina/ambiente.md
      - Github: Disciplina/github.md
      - Mkdocs: Disciplina/mkdocs.md
      - CodeSpace: Disciplina/codespace.md
      - Avaliações: Disciplina/avaliacoes.md
  - Iniciação: 
      - Index: Iniciacao/index.md
      - Pesquisa: Iniciacao/pesquisa.md
      - 5w2h: Iniciacao/5w2h.md
      - Design Thinking: Iniciacao/design_thinking.md
      - Brainstorming: Iniciacao/brainstorm.md
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Prototipagem Baixa Fidelidade: Iniciacao/prototipo_baixa_fidelidade.md
  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/das.md
      - Casos de Uso: Elaboracao/casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Diagrama de Sequência: Elaboracao/diagrama_de_sequencia.md
      - Protótipo de Alta Fidelidade: Elaboracao/prototipo_alta_fidelidade.md
  - Construção:
      - Index: Construcao/index.md
      - Git Issues: Construcao/git_issues.md
      - GitHub Projects: Construcao/github_projects.md
      - CodeSpace: Construcao/codespace.md
  - Transição:
      - Index: Transicao/index.md

  - Bibliografia: Disciplina/bibliografia.md

extra_css:
  - css/extra.css

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables

  - toc:
      permalink: true

plugins:
  - minify:
      minify_html: true
  - search

theme:
  name: material
  logo: assets/ibmec_logo.png
  palette:
    
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
      color_mode: dark
      language: pt-BR
      favicon: images/favicon.png
      user_color_mode_toggle: true
  
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: simple/react
    favicon: simple/react
